# -*- coding: utf-8 -*-

from .evaluate import  EvalPlotter, MetricPlotter 
from .evaluate import ( 
    plot_unified_pca, 
    plot_learning_inspection, 
    plot_learning_inspections, 
    plot_silhouette,
    plot_dendrogram, 
    plot_dendroheat, 
    plot_loc_projection, 
    plot_model, 
    plot_reg_scoring, 
    plot_matshow, 
    plot_model_scores,
    plot2d,  
    pobj as plot_obj
    )
from .explore import EasyPlotter, QuestPlotter
from .utils import ( 
    plot_mlxtend_heatmap , 
    plot_mlxtend_matrix, 
    plot_cost_vs_epochs, 
    plot_elbow, 
    plot_clusters, 
    plot_pca_components, 
    plot_base_dendrogram, 
    plot_learning_curves, 
    plot_confusion_matrices, 
    plot_yb_confusion_matrix, 
    plot_sbs_feature_selection, 
    plot_regularization_path, 
    plot_rf_feature_importances, 
    plot_base_silhouette, 
    plot_voronoi, 
    plot_roc_curves, 
    plot_l_curve, 
    plot_taylor_diagram, 
    plot_cv, 
    plot_confidence, 
    plot_confidence_ellipse, 
    plot_text, 
    plot_cumulative_variance, 
    plot_shap_summary, 
    )

__all__= [
    "MetricPlotter", 
    "plot_unified_pca", 
    "EvalPlotter", 
    "EasyPlotter" , 
    "QuestPlotter",
    "plot_learning_inspection", 
    "plot_learning_inspections", 
    "plot_silhouette", 
    "plot_dendrogram", 
    "plot_dendroheat", 
    "viewtemplate", 
    "plot_loc_projection", 
    "plot_model", 
    "plot_reg_scoring", 
    "plot_matshow", 
    "plot_model_scores", 
    "plot2d", 
    'plot_mlxtend_heatmap' , 
    'plot_mlxtend_matrix', 
    'plot_cost_vs_epochs', 
    'plot_elbow', 
    'plot_clusters', 
    'plot_pca_components', 
    'plot_base_dendrogram', 
    'plot_learning_curves', 
    'plot_confusion_matrices', 
    'plot_yb_confusion_matrix', 
    'plot_sbs_feature_selection', 
    'plot_regularization_path', 
    'plot_rf_feature_importances', 
    'plot_base_silhouette', 
    'plot_voronoi', 
    'plot_roc_curves', 
    'plot_l_curve', 
    'plot_taylor_diagram', 
    'plot_cv', 
    'plot_confidence', 
    'plot_confidence_ellipse', 
    'plot_text', 
    'plot_obj',
    'plot_cumulative_variance', 
    'plot_shap_summary'
    ]