# -*- coding: utf-8 -*-

from ._config import PlotConfig 
from .evaluate import ( 
    EvalPlotter, 
    MetricPlotter, 
    plot_model_scores, 
    plot_reg_scoring, 
    plot_model, 
    )
from .explore import EasyPlotter, QuestPlotter
from .ts import TimeSeriesPlotter 
from .charts import ( 
    pie_charts, 
    radar_chart_in, 
    radar_chart, 
    donut_chart, 
    plot_donut_charts
    )
from .cluster import ( 
    plot_silhouette, 
    plot_silhouette_in, 
    plot_dendrogram, 
    plot_dendrogram_in, 
    plot_clusters, 
    plot_elbow, 
    plot_cluster_comparison, 
    plot_voronoi, 
)
from .dimensionality import ( 
    plot_unified_pca, 
    plot_pca_components, 
    plot_cumulative_variance, 
 )
from .feature_analysis import ( 
    plot_importances_ranking, 
    plot_rf_feature_importances, 
    plot_feature_interactions, 
    plot_variables, 
    plot_correlation_with, 
    plot_dependence, 
    plot_sbs_feature_selection, 
    plot_permutation_importance, 
    plot_regularization_path, 
    plot_feature_importances, 
   )
from .inspection  import ( 
    plot_learning_inspection, 
    plot_learning_inspections, 
    plot_loc_projection, 
    plot_matshow, 
    plot_heatmapx, 
    plot_matrix, 
    plot_sunburst, 
    plot_sankey, 
    plot_euler_diagram, 
    create_upset_plot, 
    plot_venn_diagram, 
    plot_woodland, 
    plot_l_curve, 
  )  
from .ml_viz import ( 
    plot_confusion_matrices, 
    plot_confusion_matrix_in, 
    plot_confusion_matrix, 
    plot_roc_curves, 
    plot_taylor_diagram,
    plot_taylor_diagram_in, 
    plot_cv, 
    plot_confidence, 
    plot_confidence_ellipse, 
    plot_shap_summary, 
    plot_abc_curve, 
    plot_learning_curves, 
    plot_cost_vs_epochs, 
    plot_regression_diagnostics, 
    plot_residuals_vs_fitted, 
    plot_residuals_vs_leverage, 
    plot_r2, 
    plot_cm, 
    taylor_diagram, 

 )
from .utils import ( 
    boxplot, 
    plot_r_squared, 
    plot_text, 
    plot_spatial_features, 
    plot_categorical_feature, 
    plot_sensitivity, 
    plot_spatial_distribution, 
    plot_distributions, 
    plot_dist, 
    plot_quantile_distributions, 
    plot_uncertainty, 
    plot_prediction_intervals, 
    plot_temporal_trends, 
    plot_relationship, 
    plot_fit, 
    plot_factory_ops, 
    plot_ranking, 
    plot_coverage
    )

__all__= [
    "PlotConfig", 
    
    "MetricPlotter", 
    "EvalPlotter",
    "EasyPlotter" , 
    "QuestPlotter",
    "TimeSeriesPlotter", 
    
    "pie_charts", 
    "radar_chart",
    "radar_chart_in", 
    "donut_chart", 
    "plot_donut_charts", 
    
    'plot_silhouette',
    'plot_silhouette_in',
    'plot_dendrogram',
    'plot_dendroheat',
    'plot_dendrogram_in',
    'plot_clusters',
    'plot_elbow',
    'plot_cluster_comparison',
    'plot_voronoi',
    'plot_unified_pca',
    'plot_pca_components',
    'plot_cumulative_variance', 
    
    "plot_model_scores",
    "plot_reg_scoring",
    "plot_model", 
    
    'plot_importances_ranking',
    'plot_rf_feature_importances',
    'plot_feature_interactions',
    'plot_variables',
    'plot_correlation_with',
    'plot_dependence',
    'plot_sbs_feature_selection',
    'plot_permutation_importance',
    'plot_regularization_path',  
    'plot_feature_importances', 
    
    'plot_learning_inspection',
    'plot_learning_inspections',
    'plot_loc_projection',
    'plot_matshow',
    'plot_heatmapx',
    'plot_matrix',
    'plot_sunburst',
    'plot_sankey',
    'plot_euler_diagram',
    'create_upset_plot',
    'plot_venn_diagram',
    'plot_set_matrix',
    'plot_woodland', 
    'plot_l_curve', 
    
    'plot_confusion_matrices',
    'plot_confusion_matrix_in', 
    'plot_confusion_matrix', 
    'plot_roc_curves',
    'plot_taylor_diagram',
    'plot_taylor_diagram_in', 
    'plot_cv',
    'plot_confidence',
    'plot_confidence_ellipse',
    'plot_shap_summary',
    'plot_abc_curve',
    'plot_learning_curves',
    'plot_cost_vs_epochs', 
    'plot_regression_diagnostics', 
    'plot_residuals_vs_leverage', 
    'plot_residuals_vs_fitted', 
    'plot_r2', 
    'plot_cm', 
    'taylor_diagram', 
    
    "boxplot", 
    "plot_r_squared",
    "plot_text", 
    "plot_spatial_features", 
    "plot_categorical_feature", 
    "plot_sensitivity", 
    "plot_spatial_distribution", 
    "plot_distributions", 
    "plot_dist", 
    "plot_quantile_distributions" , 
    'plot_uncertainty', 
    'plot_prediction_intervals',
    "plot_temporal_trends", 
    'plot_relationship', 
    'plot_fit', 
    'plot_factory_ops', 
    'plot_ranking', 
    'plot_coverage'
               
    ]

